import { NoteInfo, StageDefinition } from '../types';

export const PIANO_NOTES_OCTAVE_4: NoteInfo[] = [
  { id: 'C4', nameEnglish: 'C4', nameHebrew: 'דו', pitch: 261.63, octave: 4, semitoneIndex: 0, keyType: 'white' },
  { id: 'Cs4', nameEnglish: 'C♯4', nameHebrew: 'דו♯', pitch: 277.18, octave: 4, semitoneIndex: 1, keyType: 'black' },
  { id: 'D4', nameEnglish: 'D4', nameHebrew: 'רה', pitch: 293.66, octave: 4, semitoneIndex: 2, keyType: 'white' },
  { id: 'Ds4', nameEnglish: 'D♯4', nameHebrew: 'רה♯', pitch: 311.13, octave: 4, semitoneIndex: 3, keyType: 'black' },
  { id: 'E4', nameEnglish: 'E4', nameHebrew: 'מי', pitch: 329.63, octave: 4, semitoneIndex: 4, keyType: 'white' },
  { id: 'F4', nameEnglish: 'F4', nameHebrew: 'פה', pitch: 349.23, octave: 4, semitoneIndex: 5, keyType: 'white' },
  { id: 'Fs4', nameEnglish: 'F♯4', nameHebrew: 'פה♯', pitch: 369.99, octave: 4, semitoneIndex: 6, keyType: 'black' },
  { id: 'G4', nameEnglish: 'G4', nameHebrew: 'סול', pitch: 392.00, octave: 4, semitoneIndex: 7, keyType: 'white' },
  { id: 'Gs4', nameEnglish: 'G♯4', nameHebrew: 'סול♯', pitch: 415.30, octave: 4, semitoneIndex: 8, keyType: 'black' },
  { id: 'A4', nameEnglish: 'A4', nameHebrew: 'לה', pitch: 440.00, octave: 4, semitoneIndex: 9, keyType: 'white' },
  { id: 'As4', nameEnglish: 'A♯4', nameHebrew: 'לה♯', pitch: 466.16, octave: 4, semitoneIndex: 10, keyType: 'black' },
  { id: 'B4', nameEnglish: 'B4', nameHebrew: 'סי', pitch: 493.88, octave: 4, semitoneIndex: 11, keyType: 'white' },
];

export const PIANO_NOTES_OCTAVE_5: NoteInfo[] = [
  { id: 'C5', nameEnglish: 'C5', nameHebrew: 'דו²', pitch: 523.25, octave: 5, semitoneIndex: 12, keyType: 'white' },
  { id: 'Cs5', nameEnglish: 'C♯5', nameHebrew: 'דו♯²', pitch: 554.37, octave: 5, semitoneIndex: 13, keyType: 'black' },
  { id: 'D5', nameEnglish: 'D5', nameHebrew: 'רה²', pitch: 587.33, octave: 5, semitoneIndex: 14, keyType: 'white' },
  { id: 'Ds5', nameEnglish: 'D♯5', nameHebrew: 'רה♯²', pitch: 622.25, octave: 5, semitoneIndex: 15, keyType: 'black' },
  { id: 'E5', nameEnglish: 'E5', nameHebrew: 'מי²', pitch: 659.25, octave: 5, semitoneIndex: 16, keyType: 'white' },
  { id: 'F5', nameEnglish: 'F5', nameHebrew: 'פה²', pitch: 698.46, octave: 5, semitoneIndex: 17, keyType: 'white' },
  { id: 'Fs5', nameEnglish: 'F♯5', nameHebrew: 'פה♯²', pitch: 739.99, octave: 5, semitoneIndex: 18, keyType: 'black' },
  { id: 'G5', nameEnglish: 'G5', nameHebrew: 'סול²', pitch: 783.99, octave: 5, semitoneIndex: 19, keyType: 'white' },
  { id: 'Gs5', nameEnglish: 'G♯5', nameHebrew: 'סול♯²', pitch: 830.61, octave: 5, semitoneIndex: 20, keyType: 'black' },
  { id: 'A5', nameEnglish: 'A5', nameHebrew: 'לה²', pitch: 880.00, octave: 5, semitoneIndex: 21, keyType: 'white' },
  { id: 'As5', nameEnglish: 'A♯5', nameHebrew: 'לה♯²', pitch: 932.33, octave: 5, semitoneIndex: 22, keyType: 'black' },
  { id: 'B5', nameEnglish: 'B5', nameHebrew: 'סי²', pitch: 987.77, octave: 5, semitoneIndex: 23, keyType: 'white' },
];

export const PIANO_NOTES_2_OCTAVES: NoteInfo[] = [
  ...PIANO_NOTES_OCTAVE_4,
  ...PIANO_NOTES_OCTAVE_5,
];

export const STAGES_LIST: StageDefinition[] = [
  {
    id: 'direction',
    order: 1,
    name: 'שלב 1: כיוון צלילים (עלייה / ירידה / אותו תו)',
    shortName: 'כיוון צלילים',
    playedNoteCount: 2,
    requiredAnswerCount: 1,
    octaveCount: 1,
    isDirectionOnly: true,
  },
  {
    id: 'single_1_octave',
    order: 2,
    name: 'שלב 2: תו אחד באוקטבה אחת',
    shortName: 'תו 1 (אוקטבה 1)',
    playedNoteCount: 1,
    requiredAnswerCount: 1,
    octaveCount: 1,
  },
  {
    id: 'sequence_2_1_octave',
    order: 3,
    name: 'שלב 3: 2 תווים באוקטבה אחת',
    shortName: '2 תווים (אוקטבה 1)',
    playedNoteCount: 2,
    requiredAnswerCount: 2,
    octaveCount: 1,
  },
  {
    id: 'single_2_octaves',
    order: 4,
    name: 'שלב 4: תו אחד ב-2 אוקטבות',
    shortName: 'תו 1 (2 אוקטבות)',
    playedNoteCount: 1,
    requiredAnswerCount: 1,
    octaveCount: 2,
  },
  {
    id: 'last_note_3',
    order: 5,
    name: 'שלב 5: זיהוי תו אחרון ברצף 3 תווים',
    shortName: 'תו אחרון מ-3',
    playedNoteCount: 3,
    requiredAnswerCount: 1,
    octaveCount: 1,
    isLastNoteOnly: true,
  },
  {
    id: 'last_note_4',
    order: 6,
    name: 'שלב 6: זיהוי תו אחרון ברצף 4 תווים',
    shortName: 'תו אחרון מ-4',
    playedNoteCount: 4,
    requiredAnswerCount: 1,
    octaveCount: 1,
    isLastNoteOnly: true,
  },
  {
    id: 'last_note_5',
    order: 7,
    name: 'שלב 7: זיהוי תו אחרון ברצף 5 תווים',
    shortName: 'תו אחרון מ-5',
    playedNoteCount: 5,
    requiredAnswerCount: 1,
    octaveCount: 1,
    isLastNoteOnly: true,
  },
  {
    id: 'sequence_3_1_octave',
    order: 8,
    name: 'שלב 8: 3 תווים באוקטבה אחת',
    shortName: '3 תווים (אוקטבה 1)',
    playedNoteCount: 3,
    requiredAnswerCount: 3,
    octaveCount: 1,
  },
  {
    id: 'sequence_2_2_octaves',
    order: 9,
    name: 'שלב 9: 2 תווים ב-2 אוקטבות',
    shortName: '2 תווים (2 אוקטבות)',
    playedNoteCount: 2,
    requiredAnswerCount: 2,
    octaveCount: 2,
  },
];
